### ISSUE TITLE
Repo types

### ISSUE THREAD

**Issue by odcinek** [facebook/grocery-delivery#16]
Do we need any changes here after https://github.com/facebook/between-meals/pull/21 lands? I *think* not

**Comment by jaymzh** [comment]
As I said in your PR, you will completely break a path of GD... those changes cannot happen as they currently stand.

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
