### ISSUE TITLE
Changes not reflected in chef-manage/knife cookbook list

### ISSUE THREAD

**Issue by discentem** [facebook/grocery-delivery#29]
`/var/chef/grocery_delivery_work/ops/cookbooks` has the up-to-date chef data after a grocery delivery run but chef manage doesn’t reflect the changes. I don't think the knife upload is occurring correctly.

How should I investigate this discrepancy?

**Comment by discentem** [comment]
(I don't think this is an issue with the code base, just my attempt to use it)

**Comment by jaymzh** [comment]
What do the logs show?

**Comment by discentem** [comment]
I am not sure which logs to look at. None of the logs in `/var/log/opscode` seemed to give relevant info.

**Comment by jaymzh** [comment]
grocery_delivery logs to syslog by default, so /var/log/messages or /var/log/syslog depending on your distro.

**Comment by discentem** [comment]
Here is the log output from grocery_delivery:
`Mar 12 18:00:11 ubuntu grocery-delivery[15137]: WARN: Attempting to acquire lock
Mar 12 18:00:11 ubuntu grocery-delivery[15137]: WARN: Lock acquired
Mar 12 18:00:11 ubuntu grocery-delivery[15137]: WARN: Updating repo
Mar 12 18:00:11 ubuntu grocery-delivery[15137]: WARN: Determing changes... from 726f43906d971904b0de0aa4db2888a78a05053b to 00efc2598d60e625c09142c33fe00a42d4bc36e9
Mar 12 18:00:11 ubuntu grocery-delivery[15137]: WARN: Added cookbooks: []
Mar 12 18:00:11 ubuntu grocery-delivery[15137]: WARN: Deleted cookbooks: []
Mar 12 18:00:11 ubuntu grocery-delivery[15137]: WARN: Added roles: []
Mar 12 18:00:11 ubuntu grocery-delivery[15137]: WARN: Deleted roles: []
Mar 12 18:00:11 ubuntu grocery-delivery[15137]: WARN: Added databags: []
Mar 12 18:00:11 ubuntu grocery-delivery[15137]: WARN: Deleted databags: []
Mar 12 18:00:11 ubuntu grocery-delivery[15137]: WARN: Success at 00efc2598d60e625c09142c33fe00a42d4bc36e9`

Despite making changes to a cookbook named "test" and the local git repo being updated, knife cookbook list nor chef manage show the latest changes to "test".

**Comment by discentem** [comment]
Configuration issue. Closing.
