### ISSUE TITLE
Timestamp option (--t or -T) does not work

### ISSUE THREAD

**Issue by metropolio** [facebook/grocery-delivery#37]
I was testing out GD and notice that the timestamp option doesn't produce timestamps in the output, even with upping the verbosity level. Would be handy when debugging when GD fails. Examples below:

```
root@localhost:~# /opt/chefdk/embedded/bin/grocery-delivery --timestamp -vv
WARN: Attempting to acquire lock
WARN: Lock acquired
WARN: Updating repo
DEBUG: Reading /var/chef/grocery_delivery_work/gd_revision
WARN: Repo has not changed, nothing to do...
WARN: Success at 14a40f45c0685b17005355004284163e546d9686
root@localhost:~# /opt/chefdk/embedded/bin/grocery-delivery --T -vv
WARN: Attempting to acquire lock
WARN: Lock acquired
WARN: Updating repo
DEBUG: Reading /var/chef/grocery_delivery_work/gd_revision
WARN: Repo has not changed, nothing to do...
WARN: Success at 14a40f45c0685b17005355004284163e546d9686
```

**Comment by jaymzh** [comment]
Sorry for the delay I missed this bug.

You're right - it's totally unimplemented. Probably a leftover from the previous implementation. :(

We should probably just remove the option. We're not using Logger (other than a couple of it's const's), just Sysloging. We expect the timestamps to come from syslog.
