### ISSUE TITLE
Install Instructions for Chef Automate

### ISSUE THREAD

**Issue by nottooshort** [facebook/grocery-delivery#65]
The days of chef server are gone.

Chef Automate bundles Infra and /opt/opscode/ is no longer part of the installation.

```
Version: 2
  CLI Build: 20221006204445
  Server Build: 4.3.0
```

I tried looking through the new DIR's and found that chef automate \ infra is now installed under /hab/*

For the life of me, i cannot find a relative directory or /embedded/ to install GD. Hoping there's something I don't know and that GD is supported on the latest version.

The closes thing i found was...

```
root@chef:/hab/pkgs/core/ruby27/2.7.5/20220312100031/bin# ls
bundle  bundler  erb  gem  irb  racc  racc2y  rake  rdoc  ri  ruby  update_rubygems  y2racc
```

**Comment by jaymzh** [comment]
Chef server is not gone...

Yes, automate uses Habitat packages under the hood, but chef-infra-server is still optionally distributed as an omnibus package.
